// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oscrvqfpsrmpnqzndtyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zY3J2cWZwc3JtcG5xem5kdHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDQ5ODQsImV4cCI6MjA2ODg4MDk4NH0.4JK4zOg-PtVZbpGVGS8Ky36xWeUMYDL6ke_ezfrbwMk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});